### ISSUE TITLE
memory issue with qrecvc

### ISSUE THREAD

**Issue by Codedial06** [adis300/ccmath#1]
Hi, thanks for this great piece of work!

at the end of qrecvc i had to change this:

 ev[k]=ev[k]*cc-y; dp[k-1]=ev[k]*sc; ev[k]=ev[k]*cc+d; 

to this:
 ev[k]=ev[k]*cc-y;
 if (k>0) dp[k-1]=ev[k]*sc;
 ev[k]=ev[k]*cc+d; 

because k can get 0 and then the machine tries to write outside of the acceptable heap area.

**Comment by adis300** [comment]
Thanks. It's been fixed in the latest commit according to your suggestion.
